# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alexander Justin Kerchum
title: Senior Software Engineer
email: KerchumA222@gmail.com
website: resume.kerchum.dev

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  KerchumA222
stackoverflow_username: "4289626"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: alexander-kerchum-7532b75b
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am Alex; this page is a work in progress.
  My team nick-named me 'lint-roller'

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Autosoft DMS
        link: autosoftdms.com
        # link_text: boringcompany.com
        sub_title: Senior Software Engineer
        caption: November 2018 - Present
        quote: >
          Autosoft is an innovative technology platform that has been recognized as the All-Time Most Recommended DMS.
        description: | # this will include new lines to allow paragraphs
            .NET, Angular, AngularJS, DevOps
      - layout: left
        title: Youngstown State University
        link: ysu.edu
        # link_text: boringcompany.com
        sub_title: Web Application Specialist/Programmer Analyst 4
        caption: 2016-2020
        quote: >
          An Institution of Opportunity: YSU inspires individuals, enhances futures, and enriches lives.
        description: | # this will include new lines to allow paragraphs
          Responsibilities include: Optimizing existing codebases; repairing reported bugs; building
          new requested features and software; <mark>Groovy</mark>/<mark>Grails</mark> development; full stack web
          development; maintaining and updating server-side software; building and deploying web
          applications to <mark>Linux</mark> servers; provisioning software for Linux servers; <mark>open source</mark>
          contributions; <mark>accessibility</mark> compliance (Section 508 and WCAG 2.0 AA+); REST API
          development; utilize Amazon Web Services; building and maintaining <mark>PL/SQL</mark> packages in
          Oracle; working with <mark>Ellucian Banner</mark>; Set up and maintain team version control system
          (Git via <mark>GitLab</mark>).
      - layout: left
        title: Youngstown State University
        link: ysu.edu
        # link_text: boringcompany.com
        sub_title: Web Programmer/CMS Developer
        caption: 2012-2015
        quote: >
          An Institution of Opportunity: YSU inspires individuals, enhances futures, and enriches lives.
        description: | # this will include new lines to allow paragraphs
          Responsibilities include: Timely completion of projects involving database access
          (retrieval, storage, joins), content management systems (ContentM, Drupal, custom
          systems), and public interfaces; exploring new technologies; optimizing/repairing existing
          codebases; working efectively in a small team; Groovy/Grails, Laravel, and AngularJS
          development;

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Youngstown State University
        caption: 2016
        sub_title: BS Computer Science
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          I spent much of my time at the university working on the student web team.
          This experience kick-started my career and exposed me to real world requirements.

  - title: Outside of work
    layout: text
    content: | # this will include new lines to allow paragraphs
      I love working on cars. Cars and computers have a lot of overlap, and I love that too.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
