# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alexander Justin Kerchum
title: Senior/Lead Software Engineer
email: KerchumA222@gmail.com
website: resume.kerchum.dev

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  KerchumA222
stackoverflow_username: "4289626"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: alexander-kerchum-7532b75b
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  I am passionate about doing software development the right way: this means striking the right balance between future-proofing and keeping it simple. I love getting into the flow and making magic on my screen. I believe a little bit of research and questioning can lead to a drastically better product, and a healthier relationship between engineering and product.
  I love solving harder problems; it helps me express creativity and artisanship.
  I value concise, honest, and open communication. This includes accepting criticism without taking it personally, and acting on it to improve myself and my work. 
  I generally learn technical topics and domain knowledge quickly. I return to exceptionally challenging topics over and over again, improving my capability in those areas over time.
  I became a certified scrum master when I became a team lead and I feel that the subjects learned during that, coupled with actual experience leading, have made me a very effective developer advocate. I think this is absolutely essential for a healthy team.
  I enjoy imparting new knowledge on others: sometimes this means showing my team something cool I recently learned, and other times it might mean mentoring another engineer in an area where I am an expert.
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Upstart
        link: upstart.com
        # link_text: boringcompany.com
        sub_title: Senior Software Engineer
        caption: 2022 - Present
        quote: >
          Upstart's mission is to enable effortless credit based on true risk.
        # description: |
        #   Responsibilities include:
        #   Identify and resolve the most impactful issues facing my team
        #   Selected accomplishments:
        #    - Advocated for containerizing an existing application and played a critical role in delivering on that initiative, resulting in vast and immediate improvements for developer experience and runtime performance
      - layout: left
        title: Autosoft DMS
        link: autosoftdms.com
        # link_text: boringcompany.com
        sub_title: Senior Software Engineer/Team Lead (CSM)
        caption: 2018 - 2022
        quote: >
          Autosoft is an innovative technology platform that has been recognized as the All-Time Most Recommended DMS.
        description: | # this will include new lines to allow paragraphs
          Responsibilities include: Maintaining and building a multi-tenant <mark>SaaS</mark> application used by thousands of organizations across the United States.
          Helping the organization transition from <mark>SOA</mark> to a <mark>Microservice</mark> architecture.
          Facilitating a culture of collaboration in several teams across the platform.
          Advocating on behalf of other engineers to reduce stress and improve productivity.
          Leading platform-wide technical initiatives and resolving tech-debt.
          Coordinating implementation efforts within and across teams.
          Teaching and advocating for true software craftsmanship across the organization.
          Selected accomplishments:
           - Transitioned the development organization from <mark>SVN</mark> to <mark>Git</mark> (several repositories with tens of thousands of commits retained in history)
           - Resolved several Severity 1 outages in an individual and team oriented setting.
           - Lead the effort to transition from <mark>AngularJS</mark> to <mark>Angular</mark> (multiple approaches taken)
           - Leadership role in evolving services into <mark>microservices</mark>
      - layout: left
        title: Youngstown State University
        link: ysu.edu
        # link_text: boringcompany.com
        sub_title: Web Application Specialist/Programmer Analyst 4
        caption: 2016-2020
        quote: >
          An Institution of Opportunity: YSU inspires individuals, enhances futures, and enriches lives.
        description: | # this will include new lines to allow paragraphs
          Responsibilities include: Optimizing existing codebases; repairing reported bugs; building
          new requested features and software; <mark>Groovy</mark>/<mark>Grails</mark> development; full stack web
          development; maintaining and updating server-side software; building and deploying web
          applications to <mark>Linux</mark> servers; provisioning software for Linux servers; <mark>open source</mark>
          contributions; <mark>accessibility</mark> compliance (Section 508 and WCAG 2.0 AA+); REST API
          development; utilize Amazon Web Services; building and maintaining <mark>PL/SQL</mark> packages in
          Oracle; working with <mark>Ellucian Banner</mark>; Set up and maintain team version control system
          (Git via <mark>GitLab</mark>).
      - layout: left
        title: Youngstown State University
        link: ysu.edu
        # link_text: boringcompany.com
        sub_title: Web Programmer/CMS Developer
        caption: 2012-2015
        quote: >
          An Institution of Opportunity: YSU inspires individuals, enhances futures, and enriches lives.
        description: | # this will include new lines to allow paragraphs
          Responsibilities include: Timely completion of projects involving database access
          (retrieval, storage, joins), content management systems (ContentM, Drupal, custom
          systems), and public interfaces; exploring new technologies; optimizing/repairing existing
          codebases; working efectively in a small team; Groovy/Grails, Laravel, and AngularJS
          development;

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Youngstown State University
        caption: 2016
        sub_title: BS Computer Science
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          I spent much of my time at the university working on the student web team.
          This experience kick-started my career and exposed me to real world requirements.

  - title: Outside of work
    layout: text
    content: | # this will include new lines to allow paragraphs
      I love working on cars. Cars and computers have a lot of overlap, and I love that too.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
